# -*- coding: utf-8 -*-
"""Semana_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EaqaAdhHwFDPsjQTL9nbMPTh-CLORrQ8

# Semana 2

### Etapa 1: Definição de Requisitos

- User Story:
  - Como estudante, desejo registrar minhas despesas diárias para identificar categorias de maior consumo.

- Critérios de Aceite (Validação):
  - O valor da despesa deve ser estritamente positivo (>0).
  - A data deve seguir o formato de objeto de tempo do Python (datetime).
  - A categoria deve pertencer a uma lista pré-definida de valores válidos.


### MERMAID
```mermaid
graph TD
    A[Início: Receber Despesa] --> B{Valor > 0?}
    B -- Não --> E[Retornar Erro: Valor Inválido]
    B -- Sim --> C{Data é datetime?}
    C -- Não --> F[Retornar Erro: Data Inválida]
    C -- Sim --> D{Categoria em CATEGORIAS_VALIDAS?}
    D -- Não --> G[Retornar Erro: Categoria Inválida]
    D -- Sim --> H[Registrar com Sucesso]
 ```

### Etapa 2: Implementação da Estrutura de Dados
"""

from datetime import datetime

# Lista de categorias permitidas (Normalização Lógica)
CATEGORIAS_VALIDAS = ["Alimentacao", "Transporte", "Educacao", "Lazer"]

# Exemplo de registro de despesa (Atributos da Entidade)
nova_despesa = {
    "valor": 45.50,
    "data": datetime.now(),
    "categoria": "Alimentacao",
    "estudante_id": 101
}

"""### Etapa 3: Desenvolvimento do Módulo de Validação"""

def validar_e_registrar(despesa: dict):
    # 1. Validação de Valor
    if despesa.get("valor", 0) <= 0:
        return "Erro: O valor deve ser superior a zero."

    # 2. Validação do Tipo de Data
    if not isinstance(despesa.get("data"), datetime):
        return "Erro: A data deve ser um objeto datetime válido."

    # 3. Validação de Categoria
    if despesa.get("categoria") not in CATEGORIAS_VALIDAS:
        return "Erro: Categoria não cadastrada no sistema."

    print(f"Registro realizado com sucesso: R$ {despesa['valor']:.2f} em {despesa['categoria']}")
    return True

# Teste de validação
resultado = validar_e_registrar(nova_despesa)

"""### Testes de Validação"""

# Caso 1: Válido
despesa_valida = {"valor": 45.50, "data": datetime.now(), "categoria": "Alimentacao", "estudante_id": 101}
print("Teste Válido:", validar_e_registrar(despesa_valida))

# Caso 2: Valor negativo/zero
despesa_invalida_valor = {"valor": -10.0, "data": datetime.now(), "categoria": "Transporte", "estudante_id": 101}
print("Teste Valor Inválido:", validar_e_registrar(despesa_invalida_valor))

# Caso 3: Categoria inexistente
despesa_invalida_cat = {"valor": 20.0, "data": datetime.now(), "categoria": "Jogos", "estudante_id": 101}
print("Teste Categoria Inválida:", validar_e_registrar(despesa_invalida_cat))

"""### Etapa 4: Análise da Consistência para KPIs

* **Consistência:** A validação estrita de valores positivos ($> 0$) impede que entradas com sinais trocados (como estornos ou erros de digitação) reduzam artificialmente o somatório total das despesas ou gerem uma média aritmética negativa, garantindo que o KPI de Gasto Médio reflita apenas o consumo real.
* **Padronização:** A restrição a um conjunto fixo de categorias evita redundâncias e fragmentações de dados (ex.: "alimentação", "Alimentacao", "comida"), permitindo agrupamentos (`GROUP BY`) consistentes e garantindo que os gráficos de pizza ou barras contenham apenas fatias representativas e sem duplicidades semânticas.
* **Extensibilidade:** Para incluir o meio de pagamento, basta:
  1. Definir uma nova lista de controle: `MEIOS_PAGAMENTO = ["Dinheiro", "Cartao", "PIX"]`.
  2. Adicionar o campo `"meio_pagamento"` no dicionário da entidade.
  3. Incluir uma nova cláusula de validação na função checando `if despesa.get("meio_pagamento") not in MEIOS_PAGAMENTO`.
"""